name: Testing

on: [push]

jobs:
  build:
    name: "Frontend tests"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create .env file
      if: always()
      run: |
        cd client
        touch .env
        echo SKIP_PREFLIGHT_CHECK=true >> .env
        echo CI=true >> .env
        cat .env
    - name: install node dependencies
      if: always()
      run: cd client; yarn install
    - name: Run all tests
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      if: always()
      run: cd client; yarn firebase emulators:exec "yarn test --detectOpenHandles"
    - name: Notify on failure
      if: failure()
      run: echo 'Some tests in this test suite do not pass'
  backendTests:
    name: "Backend Tests"
    runs-on: ubuntu-latest
    steps:
    - name: Run all tests
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_KEY }}
        TESTING: "true"
      if: always()
      run: mvn test
    - name: Notify on failure
      if: failure()
      run: echo 'Some tests in this test suite do not pass'